//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string Major { get; set; }
        public string PhoneNumber { get; set; }
        public string Sex { get; set; }
        public Nullable<int> idTypeStudent { get; set; }
        public string idCourse { get; set; }
    
        public virtual TypeStudent TypeStudent { get; set; }
        public virtual Course Course { get; set; }
    }
}
